# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(max_length=1)),
                ('pin', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.CharField(choices=[('in', 'checked_in'), ('out', 'checked_out')], max_length=3)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Child')),
            ],
        ),
    ]
